# -*- coding: utf-8 -*-
"""Data_Engineering_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjXMcaxMIi5VzsnpWk2vlGwfGaV7Syl9
"""

import numpy as np
a = np.array([1,2,3,4,5])
print(f"a is equal to {a} and its type is {type(a)}")

"""Slices"""

print(a[0])

"""Matrix

"""

a_multi = np.array([[1,2,3,4],
                    [4,5,6,7],
                    [8,9,10,11]])
a_multi

begin = 0
end = 10
step_size = 2
seq = np.arange(begin,end,step_size)
seq

x = 1000
pos = 0
a = np.array([1,2,3])
a = np.insert(a,pos,x)
a
# documentation for functions: help(np.insert)

# delete array

b = np.array([[1,2,3],[4,5,6]])

index = 1
axis = 0
b = np.delete(b,index,axis)
b